In [ ]:
# create an array

In [ ]:
import numpy as np
x = np.array([1, 2, 3]) # Let numpy choose the datatype
print(x)
print(x.dtype)

In [ ]:
import numpy as np

z = np.array([[1,2,3],[5,6,7]])

print(z)
print(z.dtype)



[[1 2 3]
 [5 6 7]]
int64


In [ ]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)
print(x.dtype)

[1. 2. 3.]
float64


In [ ]:
import numpy as np
x = np.arange(30)
print(x)
print(x.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
int64


In [ ]:
import numpy as np
x = np.linspace(0, 4, 4)  # 建立一個 array, 在 0 與 3 的範圍之間 等分 4 個點
print(x)
print(x.dtype)

[0.         1.33333333 2.66666667 4.        ]
float64


In [ ]:
import numpy as np
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)

int64


In [ ]:
import numpy as np
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype) 

float64


In [ ]:
import numpy as np
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)

int64


In [ ]:
# basic arithmetic operation

In [ ]:
a = np.array([5, 6, 7, 8])
b = np.array([1, 3, 5, 7])
c = a + b
print(c)

[ 6  9 12 15]


In [ ]:
a = np.array([5, 6, 7, 8])
b = np.array([1, 3, 5, 7])
c = a - b
print(c)

In [ ]:
a = np.array([5, 6, 7, 8])
b = np.array([1, 3, 5, 7])
c = a * b
print(c)

[ 5 18 35 56]


In [ ]:
a = np.array([5, 6, 7, 8])
b = np.array([1, 3, 5, 7])
c = a / b
print(c)

[5.         2.         1.4        1.14285714]


In [ ]:
a = np.array([5, 6, 7, 8])
c = a**2
print(c)

NameError: ignored