In [ ]:
import numpy as np

In [ ]:
a = np.zeros((3,2))   # Create an array of all zeros

In [ ]:
print(a)              

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((3,2))    # Create an array of all ones
print(b)            

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
c = np.full((3,2), 7)  # Create a constant array
print(c)             

[[7 7]
 [7 7]
 [7 7]]


In [ ]:
d = np.eye(3)         # Create a 3x3 identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e = np.random.random((3,2))  # Create an array filled with random values
print(e)

[[0.04035962 0.77458745]
 [0.50149249 0.77608274]
 [0.22258492 0.78842361]]
