In [2]:
import numpy as np

In [16]:
a= np.arange(6)
print(a)

[0 1 2 3 4 5]


In [17]:
b = np.reshape(a, (3,2))
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [18]:
c = np.array([[1,2],[3,4],[5,6]])
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
d = np.transpose(c)
print(d)

[[1 3 5]
 [2 4 6]]


In [21]:
print(np.sum(c, axis=0)) 

[ 9 12]


In [ ]:
print(np.sum(d, axis=1))

[ 9 12]
