In [ ]:
import numpy as np 

In [ ]:
x = np.arange(3)
print(x)

[0 1 2]


In [ ]:
x = np.arange(0,3)
print(x)

[0 1 2]


In [ ]:
x = np.arange(0,1, 0.1)  # start from 0 and up to 1, each step is 0.1
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
