In [2]:
import numpy as np 

In [2]:
# rand函數根據給定維度生成[0,1)之間的數據，包含0，不包含1
# 返回值为指定维度的array

In [3]:
x = np.random.rand(3)
x

array([0.00112402, 0.13763995, 0.09600346])

In [7]:
x = np.random.rand(3,2)
x

array([[0.95400371, 0.85921843],
       [0.95524696, 0.66068659],
       [0.95131918, 0.54838582]])

In [34]:
x = np.arange(0,3, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [6]:
for i in range(8):
    x = np.random.randint(10)
    print(x, end=',')

6,0,8,1,5,4,3,7,